version: '3.8'

services:
  my-rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: my-rabbit
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    depends_on:
      my-rabbit:
        condition: service_healthy
    networks:
      - mynetwork

  rssreadercontainer:
    image: rssreadercontainer
    build:
      context: .
      dockerfile: RssReaderContainer/Dockerfile
    depends_on:
      my-rabbit:
        condition: service_healthy
    environment:
      - RABBITMQ_CONNECTIONSTRING=my-rabbit  
    networks:
      - mynetwork

  rssqueueconsumer:
    image: rssqueueconsumer
    build:
      context: .
      dockerfile: RssQueueConsumer/Dockerfile
    depends_on:
      my-rabbit:
        condition: service_healthy
    environment:
      - RABBITMQ_CONNECTIONSTRING=my-rabbit
      - MONGO_CONNECTIONSTRING=mongodb://root:123456@mongo:27017
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
