
version: '3.4'

services:
  rssreadercontainer:
    image: rssreadercontainer
    build:
      context: .
      dockerfile: RssReaderContainer/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
