name: CI
run-name: Executado por ${{ github.actor}} em ${{ github.run_started_at }}
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  publish-to-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Build and push Rss Reader
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./RssReaderContainer/Dockerfile
        push: true
        tags: | 
          dududeveloper/rss-reader-container:latest
          dududeveloper/rss-reader-container:v${{github.run_number}}

    - name: Build and push Rss Consumer
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./RssQueueConsumer/Dockerfile
        push: true
        tags: | 
          dududeveloper/rss-queue-consumer:latest
          dududeveloper/rss-queue-consumer:v${{github.run_number}}
